config/routes.rb
Rails.application.routes.draw do
  get 'animals/adoptions' => 'animals#adoptions'
  get 'animals/intakes' => 'animals#intakes'
  
  resources :enclosures
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'animals#intakes'
end

app/models/enclosure.rb
class Enclosure < ApplicationRecord
  belongs_to :animal, optional: true
end

app/controllers/enclosures_controller.rb
class EnclosuresController < ApplicationController
  before_action :set_enclosure, only: [:show, :edit, :update, :destroy]

  # GET /enclosures
  # GET /enclosures.json
  def index
    @enclosures = Enclosure.all
  end

  # GET /enclosures/1
  # GET /enclosures/1.json
  def show
  end

  # GET /enclosures/new
  def new
    @enclosure = Enclosure.new
  end

  # GET /enclosures/1/edit
  def edit
  end

  # POST /enclosures
  # POST /enclosures.json
  def create
    @enclosure = Enclosure.new(enclosure_params)

    respond_to do |format|
      if @enclosure.save
        format.html { redirect_to @enclosure, notice: 'Enclosure was successfully created.' }
        format.json { render :show, status: :created, location: @enclosure }
      else
        format.html { render :new }
        format.json { render json: @enclosure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enclosures/1
  # PATCH/PUT /enclosures/1.json
  def update
    respond_to do |format|
      if @enclosure.update(enclosure_params)
        format.html { redirect_to @enclosure, notice: 'Enclosure was successfully updated.' }
        format.json { render :show, status: :ok, location: @enclosure }
      else
        format.html { render :edit }
        format.json { render json: @enclosure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enclosures/1
  # DELETE /enclosures/1.json
  def destroy
    @enclosure.destroy
    respond_to do |format|
      format.html { redirect_to enclosures_url, notice: 'Enclosure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enclosure
      @enclosure = Enclosure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enclosure_params
      params.require(:enclosure).permit(:name)
    end
end

app/helpers/enclosures_helper.rb
module EnclosuresHelper
end

app/views/enclosures/_form.html.erb
<%= form_with(model: enclosure, local: true) do |form| %>
  <% if enclosure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enclosure.errors.count, "error") %> prohibited this enclosure from being saved:</h2>

      <ul>
      <% enclosure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enclosures/_map.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.1.2, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 796 334" style="enable-background:new 0 0 796 334;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#008B93;stroke:#FFFFFF;stroke-miterlimit:10;}
	.st1{fill:#FFFFFF;}
	.st2{font-family:'SFProDisplay-Semibold';}
	.st3{font-size:13px;}
	.st4{fill:#FFFFFF;stroke:#008B93;stroke-width:2;stroke-miterlimit:10;}
	.st5{fill:#006A70;}
	.st6{fill:#008B93;}
	.st7{fill:none;stroke:#008B93;stroke-width:2;stroke-miterlimit:10;}
	.st8{fill:#008B6A;}
	.st9{fill:#009A6A;}
	.st10{opacity:0.32;}
	.st11{fill:#EDEDED;stroke:#FFFFFF;stroke-miterlimit:10;}
	.occupied{fill: #ee2740; stroke: #FFFFFF; stroke-miterlimit:10;}
</style>
<g id="Map">
	<path class="st0" d="M133,261.5v20c-11,0-20-9-20-20H0.1v72.1H137v-72.1H133z"/>
	<path class="st0" d="M270.3,261.5v20c-11,0-20-9-20-20H137.4v72.1h136.9v-72.1H270.3z"/>
	<path class="st0" d="M507.4,261.5c0,11-9,20-20,20v-20h-4v72.1h125.9v-72.1H507.4z"/>
	<path class="st0" d="M633,261.5c0,11-9,20-20,20v-20h-6v72.1h78.8v-72.1H633z"/>
	<g>
		<g>
			<text transform="matrix(1 0 0 1 32.3614 296.6043)" class="st1 st2 st3">Examination</text>
		</g>
		<text transform="matrix(1 0 0 1 51.5614 313.4043)" class="st1 st2 st3">Room</text>
	</g>
	<g>
		<text transform="matrix(1 0 0 1 152.204 303.0044)" class="st1 st2 st3">Laundry &amp; Storage</text>
	</g>
	<rect x="1.8" y="65.3" class="st4" width="151.3" height="164.4"/>
	<g>
		<text transform="matrix(1 0 0 1 45.5557 89.605)" class="st5 st2 st3">Quarantine</text>
	</g>
	<rect x="153.1" y="65.2" class="st4" width="301" height="164.4"/>
	<g>
		<text transform="matrix(1 0 0 1 258.4364 89.6051)" class="st5 st2 st3">Adoptable Dogs</text>
	</g>
	<rect x="454.1" y="65.3" class="st4" width="230.9" height="164.4"/>
	<g>
		<text transform="matrix(1 0 0 1 526.1037 89.6049)" class="st5 st2 st3">Adoptable Cats</text>
	</g>
	<rect x="687.9" y="64.3" class="st6" width="108" height="94.1"/>
	<g>
		<text transform="matrix(1 0 0 1 622.6263 296.6042)" class="st1 st2 st3">Bonding</text>
		<text transform="matrix(1 0 0 1 629.4263 313.4042)" class="st1 st2 st3">Room</text>
	</g>
	<g>
		<text transform="matrix(1 0 0 1 500.8658 303.0038)" class="st1 st2 st3">Small Creatures</text>
	</g>
	<g>
		<text transform="matrix(1 0 0 1 705.7567 112.2526)" class="st1 st2 st3">Staff Offices</text>
	</g>
	<rect x="274.3" y="261.5" class="st0" width="120.2" height="72.1"/>
	<g>
		<g>
			<text transform="matrix(1 0 0 1 303.3688 296.6043)" class="st1 st2 st3">Training &amp; </text>
		</g>
		<g>
			<text transform="matrix(1 0 0 1 287.5688 313.4043)" class="st1 st2 st3">Outreach Center</text>
		</g>
	</g>
	<text transform="matrix(1 0 0 1 736.2901 297.6044)" class="st6 st2 st3">Visitor</text>
	<text transform="matrix(1 0 0 1 728.0901 313.2044)" class="st6 st2 st3">Check-In</text>
	<ellipse class="st1" cx="31.3" cy="229.8" rx="13" ry="10"/>
	<path class="st1" d="M613,281.5L613,281.5c11,0,20-9,20-20l0,0h-20V281.5z"/>
	<rect x="718.8" y="261.5" class="st6" width="75" height="8"/>
	<path class="st1" d="M390.5,281.5L390.5,281.5c-11,0-20-9-20-20l0,0h20V281.5z"/>
	<ellipse class="st1" cx="382.5" cy="229.6" rx="13" ry="10"/>
	<ellipse class="st1" cx="655" cy="229.6" rx="13" ry="10"/>
	<ellipse class="st1" cx="382.5" cy="64.3" rx="13" ry="10"/>
	<polyline class="st7" points="794.9,156.3 794.9,333.6 718.8,333.6 	"/>
	<g>
		<rect x="1.8" y="0.3" class="st8" width="451.9" height="62"/>
		<rect x="1.8" y="44.8" class="st9" width="451.9" height="9"/>
		<rect x="1.8" y="26.8" class="st9" width="451.9" height="9"/>
		<rect x="1.8" y="8.8" class="st9" width="451.9" height="9"/>
	</g>
	<rect x="424.8" y="261.5" class="st0" width="58.2" height="72.1"/>
	<g class="st10">
		<g>
			<g>
				<circle class="st1" cx="449.5" cy="290.1" r="2.5"/>
			</g>
		</g>
		<g>
			<g>
				<path class="st1" d="M453.3,300.6l-0.6-5.7c-0.1-0.6-0.6-1.1-1.2-1.1h-0.7c-0.2,0-0.3,0.1-0.4,0.2l-0.8,0.8l-0.8-0.8
					c-0.1-0.1-0.3-0.2-0.4-0.2h-0.7c-0.6,0-1.2,0.5-1.2,1.1l-0.6,5.7c0,0.2,0,0.3,0.2,0.5c0.1,0.1,0.3,0.2,0.5,0.2h0.7l0.5,5.1
					c0.1,0.6,0.6,1.1,1.2,1.1h1.4c0.6,0,1.2-0.5,1.2-1.1l0.5-5.1h0.7c0.2,0,0.3-0.1,0.5-0.2C453.2,301,453.3,300.8,453.3,300.6z"/>
			</g>
		</g>
		<g>
			<g>
				<circle class="st1" cx="458.3" cy="290.1" r="2.5"/>
			</g>
		</g>
		<g>
			<g>
				<path class="st1" d="M461,300.1h0.4c0.2,0,0.4-0.1,0.5-0.2s0.2-0.3,0.2-0.5l-0.6-4.4c-0.1-0.6-0.6-1.1-1.2-1.1h-3.9
					c-0.6,0-1.2,0.5-1.2,1.1l-0.6,4.4c0,0.2,0,0.4,0.2,0.5c0.1,0.1,0.3,0.2,0.5,0.2h0.4l-1,2.9c-0.1,0.2,0,0.4,0.1,0.6
					s0.3,0.3,0.5,0.3h0.7l0.5,2.7c0.1,0.6,0.6,1,1.2,1h1.4c0.6,0,1.1-0.4,1.2-1l0.5-2.7h0.7c0.2,0,0.4-0.1,0.5-0.3
					c0.1-0.2,0.1-0.4,0.1-0.6L461,300.1z"/>
			</g>
		</g>
	</g>
	<g>
		<text transform="matrix(1 0 0 1 151.2674 34.2063)" class="st1 st2 st3">Dog Training and Play Area</text>
	</g>
	<line class="st7" x1="1.8" y1="229.8" x2="1.8" y2="262.5"/>
</g>
<g id="Enclosures">
	<rect id="Quarantine 6" x="18.3" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Quarantine 5" x="57.8" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Quarantine 4" x="97.2" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Quarantine 3" x="97.2" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Quarantine 2" x="57.8" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Quarantine 1" x="18.3" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 14" x="165.6" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 13" x="205" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 12" x="244.5" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 11" x="283.9" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 10" x="323.3" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 9" x="362.7" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 8" x="402.1" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 7" x="402.1" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 6" x="362.7" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 5" x="323.3" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 4" x="283.9" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 3" x="244.5" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 2" x="205" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Kennel 1" x="165.6" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 10" x="471" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 9" x="510.4" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 8" x="549.8" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 7" x="589.2" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 6" x="628.6" y="158.4" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 5" x="628.6" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 4" x="589.2" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 3" x="549.8" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 2" x="510.4" y="105.5" class="st11" width="39.4" height="52.9"/>
	<rect id="Cat Room 1" x="471" y="105.5" class="st11" width="39.4" height="52.9"/>
</g>
</svg>

app/views/enclosures/edit.html.erb
<h1>Editing Enclosure</h1>

<%= render 'form', enclosure: @enclosure %>

<%= link_to 'Show', @enclosure %> |
<%= link_to 'Back', enclosures_path %>

app/views/enclosures/index.html.erb
<p id="notice"><%= notice %></p>


<h1 class="mt-4">Map View</h1>
<p class="mb-4 mt-3 text-justify">Hover over the enclosures below to see where each intake is located.<br>
Click on an occupied enclosure to view the occupant's details.</p>


<div class="container py-4 px-4" style="border: 2px solid #eaeaea; border-radius: 6px;">
  <%= render 'map' %>
</div>

<table class="table table-sm mt-4 pt-4 d-none">
  <thead>
    <tr>
      <th>Location</th>
      <th>Animal</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @enclosures.each do |enclosure| %>
      <tr>
        <td><%= enclosure.name %></td>
        <td>
          <% if !enclosure.animal_id.nil? %>
            <%= Animal.find_by_id(enclosure.animal_id).name %>
          <% end %>
          
          <script>
            var enclosure_id = '<%= enclosure.name %>'
            var $enclosure = $('[id="' + enclosure_id + '"]');

            $enclosure.attr("data-toggle", "tooltip");
            
            
            <% if !enclosure.animal_id.nil? %>
              var animal_id = '<%= enclosure.animal_id %>';
              
              $enclosure.removeClass("st11").addClass("occupied");
              $enclosure.attr("title", enclosure_id + '<br><%= Animal.find_by_id(enclosure.animal_id).name %>')
              .attr("data-html", "true").attr("onclick", ("window.location.assign('/animals/" + animal_id + "');"));
            <% else %>
              $enclosure.attr("title", enclosure_id);
            <% end %>
          </script>
        </td>
        <td><%= link_to 'Show', enclosure %></td>
        <td><%= link_to 'Edit', edit_enclosure_path(enclosure) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enclosure', new_enclosure_path, :class => "d-none" %>

<script>
// initialize all toolips
  $(function () {
  $('[data-toggle="tooltip"]').tooltip()
});
</script>

app/views/enclosures/new.html.erb
<h1>New Enclosure</h1>

<%= render 'form', enclosure: @enclosure %>

<%= link_to 'Back', enclosures_path %>

app/views/enclosures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enclosure.name %>
</p>

<%= link_to 'Edit', edit_enclosure_path(@enclosure) %> |
<%= link_to 'Back', enclosures_path %>