config/routes.rb
Rails.application.routes.draw do
  get 'animals/adoptions' => 'animals#adoptions'
  get 'animals/intakes' => 'animals#intakes'
  
  resources :enclosures
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'animals#intakes'
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :enclosure, optional: true
  
  validates :name, presence: true
  validates :birthday, presence: true
  validates :intake_date, presence: true
  validates :outcome_date, presence: true
  validates :outcometype, presence: true
  
  validate :birds_livestock_and_other_cannot_be_active
  validate :intake_date_must_be_before_or_equal_to_today
  validate :birthday_must_be_before_or_equal_to_today
  validate :outcome_date_must_be_before_or_equal_to_today
  validate :outcome_date_must_be_after_or_equal_to_intake_date
  
  validate :intake_date_must_be_on_or_after_birthday



  validate :animal_must_have_a_location
  
  
  # TODO: intakeDate <= Today
  # Status: Active, Inactive
  # Status determined by outcomeDate
  
  has_attached_file :avatar
  
  # validate the attached image is jpg/png/etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  private 
    def animal_must_have_a_location
      return unless outcometype == "Active"
      errors.add(:enclosure_id, "must be selected for active animals") unless enclosure_id.present?
    end
    
    def birds_livestock_and_other_cannot_be_active
      return unless outcometype == "Active"
      errors.add(:outcometype, "cannot be active for an animal of type Bird, Livestock, or Other") unless (animaltype == "Dog" or animaltype == "Cat")
    end
  
    def intake_date_must_be_on_or_after_birthday
      return unless intake_date and birthday
      errors.add(:intake_date, "must be on or after the animal's birthday") unless intake_date >= birthday
    end
    
    def outcome_date_must_be_on_or_after_birthday
      return unless outcome_date and birthday
      errors.add(:outcome_date, "must be on or after the animal's birthday") unless outcome_date >= birthday
    end
    
    def intake_date_must_be_before_or_equal_to_today
      return unless intake_date
      errors.add(:intake_date, "cannot be later than today") unless intake_date <= Date.today
    end
    
    def birthday_must_be_before_or_equal_to_today
      return unless birthday
      errors.add(:birthday, "cannot be later than today") unless birthday <= Date.today
    end
    
    def outcome_date_must_be_before_or_equal_to_today
      return unless outcome_date
      errors.add(:outcome_date, "cannot be later than today") unless outcome_date <= Date.today
    end
    
    def outcome_date_must_be_after_or_equal_to_intake_date
      return unless outcome_date and intake_date
      errors.add(:outcome_date, "cannot be earlier than intake date") unless outcome_date >= intake_date
    end
    
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  before_action :colors, only: [:new, :create, :edit, :update]

  # GET /animals
  # GET /animals.json
  def index
    
    # check for search params
    @animals = Animal.where(
      "name like :name and animaltype like :type and outcometype like :outcometype and outcometype != 'Active'",
      {name: "%#{params[:name]}%", type: "%#{params[:type]}%", outcometype: "%#{params[:outcometype]}%"}
    )
    
    # grab number of results to display back to user
    @results_count = @animals.count
    
    # paginate results 
    @animals = @animals.order("outcome_date DESC, updated_at DESC").paginate(:page => params[:page], :per_page => 500)
    
  end
  
  # GET /animals/intakes
  def intakes
    @animals = Animal.where(outcometype: 'Active').order("animaltype, name")
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
    # initialize dates
    @animal.intake_date = @animal.birthday = @animal.outcome_date = Date.today
  end

  # GET /animals/1/edit
  def edit
    if @animal.intake_date.present?
       @animal.intake_date = @animal.intake_date.strftime("%B %-d, %Y")
    end
    
    if @animal.birthday.present?
      @animal.birthday = @animal.birthday.strftime("%B %-d, %Y")
    end
    
    if @animal.outcome_date.present?
      @animal.outcome_date = @animal.outcome_date.strftime("%B %-d, %Y")
    end
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        if !@animal.enclosure_id.nil?
          Enclosure.find_by_id(@animal.enclosure_id).update_attribute(:animal_id, @animal.id)
        end
        format.html { redirect_to @animal }
        flash[:success] = 'Record was successfully created.'
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    enclosure = @animal.enclosure_id
    
    respond_to do |format|
      if @animal.update(animal_params)
        
        if @animal.enclosure_id != enclosure && !enclosure.nil?
          Enclosure.find_by_id(enclosure).update_attribute(:animal_id, "") # clear previous
        end
        
        if !@animal.enclosure_id.nil?
          Enclosure.find_by_id(@animal.enclosure_id).update_attribute(:animal_id, @animal.id)
        end
        
        format.html { redirect_to @animal}
        flash[:success] = 'Record was successfully updated.'
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
          if !@animal.enclosure_id.nil?
        Enclosure.find_by_id(@animal.enclosure_id).update_attribute(:animal_id, "")
      end
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url }
      flash[:success] = 'Record was successfully deleted.'
      format.json { head :no_content }
    end
  end
  
  def adoptions 
  #  @animal = Animal.select("id, outcome_date").where(outcometype: "Adoption")
   # @animals = @animal.group_by { |t| t.outcome_date.year }
    if (params[:report_breed].nil?)
     breed = "Cat" #default to Cat if not present since 1st in list
    else
     breed = params[:report_breed]
    end
   
   if params[:report] == "Adoptions by Breed"
     
      @adoptions = Animal.select("breed, count(id) as adoptions").where(animaltype: "#{breed}", outcometype: "Adoption").group("breed")
      @adoptions = @adoptions.order("adoptions ASC, breed DESC").to_json
  
   elsif params[:report] == "Outcomes by Breed"

      @adoptions = Animal.select("outcometype, count(id) as totals").where(animaltype: "#{breed}").group("outcometype")
      @adoptions = @adoptions.order("totals ASC, outcometype DESC").to_json

   else
     
      if Rails.env.development?
        @animals = Animal.select("strftime('%Y', outcome_date) as 'outcome_year', count(id) as 'total_id'").where(outcometype: "Adoption").group("strftime('%Y',outcome_date)")
      else 
        #Syntax specific to PostgreSQL
        @animals = Animal.select("EXTRACT(year FROM outcome_date) as outcome_year, count(id) as total_id").where(outcometype: "Adoption").group("EXTRACT(year FROM outcome_date)")
      end
      
      @animals = @animals.order("outcome_year ASC")
      @animal_json = @animals.to_json
    end
    
    #@animals_cleaned = @animals.map{|a| {
    #  :id => a.id, :outcome_date => a.outcome_date.strftime("%Y")
    #}}
    # @animal_json = @animals_cleaned.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :birthday, :outcometype, :outcomesubtype, 
      :animaltype, :sex, :breed, :color, :intake_date, :outcome_date, :enclosure_id, :avatar)
    end
    
    def colors
      @colors = Animal.select("color").distinct.order("color")
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_adoptionbydogbreed.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>

<script>
    var data_raw = '<%= @adoptions %>'
    var data = jQuery.parseJSON(data_raw.replace(/&quot;/g,'"'));


    //set up svg using margin conventions - we'll need plenty of room on the left for labels
    var margin = {
        top: 30,
        right: 40,
        bottom: 0,
        left: 280
    };
    
    var custom_mt = <% if params[:report_breed] == "Dog" %>-500<%else %>50<% end %>
    
    var calc_height = parseInt(data.length, 10) * 20;

    var width = 960 - margin.left - margin.right,
        height = calc_height - margin.top - margin.bottom;
        
    var svg = d3.select(".container:nth-child(2)").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + custom_mt + margin.bottom )
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + custom_mt + ")");

    var x = d3.scale.linear()
        .range([0, width])
        .domain([0, d3.max(data, function (d) {
            return d.adoptions;
        })]);
    
    var y = d3.scale.ordinal()
        .rangeRoundBands([height, 0], .1)
        .domain(data.map(function (d) {
            return d.breed;
        }));

    //make y axis to show bar names
    var yAxis = d3.svg.axis()
        .scale(y)
        //no tick marks
        .tickSize(0)
        .orient("left");

    var gy = svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)

    var bars = svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("g")

    //append rects
    bars.append("rect")
        .attr("class", "bar")
        .attr("y", function (d) {
            return y(d.breed);
        })
        .attr("height", y.rangeBand())
        .attr("x", 0)
        .attr("width", function (d) {
            return x(d.adoptions);
        });

    //add a value label to the right of each bar
    bars.append("text")
        .attr("class", "label")
        //y position of the label is halfway down the bar
        .attr("y", function (d) {
            return y(d.breed) + y.rangeBand() / 2 + 4;
        })
        //x position is 3 pixels to the right of the bar
        .attr("x", function (d) {
            return x(d.adoptions) + 3;
        })
        .text(function (d) {
            return d.adoptions;
        });
        
</script>
    

app/views/animals/_adoptionsbybreed.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>

<script>
    var data_raw = '<%= @adoptions %>'
    var data = jQuery.parseJSON(data_raw.replace(/&quot;/g,'"'));


    //set up svg using margin conventions - we'll need plenty of room on the left for labels
    var margin = {
        top: 30,
        right: 40,
        bottom: 0,
        left: 280
    };
    
    var custom_mt = <% if params[:report_breed] == "Dog" %>-500<%else %>50<% end %>
    
    var calc_height = <% if params[:report_breed] == "Livestock" %>60<% else %>parseInt(data.length, 10) * 20<% end %>;

    var width = 960 - margin.left - margin.right,
        height = calc_height - margin.top - margin.bottom;
        
    var svg = d3.select(".container:nth-child(2)").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + custom_mt + margin.bottom )
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + custom_mt + ")");

    var x = d3.scale.linear()
        .range([0, width])
        .domain([0, d3.max(data, function (d) {
            return d.adoptions;
        })]);
    
    var y = d3.scale.ordinal()
        .rangeRoundBands([height, 0], .1)
        .domain(data.map(function (d) {
            return d.breed;
        }));

    //make y axis to show bar names
    var yAxis = d3.svg.axis()
        .scale(y)
        //no tick marks
        .tickSize(0)
        .orient("left");

    var gy = svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)

    var bars = svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("g")

    //append rects
    bars.append("rect")
        .attr("class", "bar")
        .attr("y", function (d) {
            return y(d.breed);
        })
        .attr("height", y.rangeBand())
        .attr("x", 0)
        .attr("width", function (d) {
            return x(d.adoptions);
        });

    //add a value label to the right of each bar
    bars.append("text")
        .attr("class", "label")
        //y position of the label is halfway down the bar
        .attr("y", function (d) {
            return y(d.breed) + y.rangeBand() / 2 + 4;
        })
        //x position is 3 pixels to the right of the bar
        .attr("x", function (d) {
            return x(d.adoptions) + 3;
        })
        .text(function (d) {
            return d.adoptions;
        });
        
</script>
    

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true, multipart: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h5 style="color: #ee2740;"><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h5>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li style="color: #ee2740;"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group form-row">
    <div class="col-4">
      <%= form.label :name %>
      <%= form.text_field :name, :class => "form-control" %>
    </div>
    
    <div class="col-4 ml-4">
      <%= form.label :intake_date %>
      <%= form.text_field :intake_date, :class => "datepicker form-control bg-white", 
      value: @animal.intake_date.present? ? @animal.intake_date.strftime("%B %-d, %Y") : "" %>
    </div>
  </div>
  

    <div class="form-group form-row">
      <div class="col-4">
        <%= form.label "Animal Type" %>
        <%= form.select(:animaltype, ['Bird', 'Cat', 'Dog', 'Livestock', 'Other'], {}, {:class => "form-control"}) %>
      </div>
      
      <div class="col-4 ml-4">
        <%= form.label "Photo" %>
        <%= form.file_field :avatar, :class => "form-control-file" %>
      </div>
    </div>

  
  <div class="form-group form-row">
    <div class="col-4">
      <%= form.label :sex %>
      <%= form.select(:sex, ['Intact Female', 'Intact Male', 'Neutered Male', 'Spayed Female',  'Unknown'], {}, { :class => "form-control" }) %>
    </div>
    
    <div class="col-4 ml-4">
      <%= form.label :birthday %>
      <%= form.text_field :birthday, :class => "datepicker form-control bg-white", 
      value: @animal.birthday.present? ? @animal.birthday.strftime("%B %-d, %Y") : "" %>
    </div>
  </div>

  <div class="form-group form-row">
    <div class="col-4">
      <%= form.label :breed %>
      <%= form.text_field :breed, list: "breeds", :class => "form-control", autocomplete: "off" %>
    </div>
    
    <div class="col-4 ml-4">
      <%= form.label :color %>
      <%= form.text_field :color, list: "colors", :class => "form-control" %>
      <datalist id="colors">
        <% @colors.each do |item| %>
          <option value="<%= item.color %>"></option>
        <% end %>
      </datalist>
    </div>
  </div>
  
  <div class="form-group form-row">
    <div class="col-4">
      <%= form.label "Status" %>
      <%= form.select(:outcometype, ['Active', 'Adoption', 'Died', 'Euthanasia', 'Missing', 'Return to Owner', 'Transfer'], {}, 
      {:class => "form-control", :id => "outcome", :onChange => "toggleEnclosures();"}) %>
    </div>
    
    <div class="col-4 ml-4"  id="enclosures">
      <%= form.label "Enclosure" %>
      <%= form.select(:enclosure_id, Enclosure.where("animal_id is null or animal_id = :id", {id: @animal.id}).order(:name).map{ |e| [e.name, e.id]}, {:include_blank => true}, {:class => "form-control", :id => "enclosuresField"}) %>
    </div>
    
    <div class="col-4 ml-4" id="outcome_date">
      <%= form.label :outcome_date %>
      <%= form.text_field :outcome_date, :class => "datepicker form-control bg-white", 
      value: @animal.outcome_date.present? ? @animal.outcome_date.strftime("%B %-d, %Y") : "" %>
    </div>
  </div>

  <div class="form-group form-row">
    <div class="col-4">
      <%= form.label "Remarks" %>
      <%= form.text_area :outcomesubtype, :class => "form-control" %>
    </div>
  </div>
  
  <div class="actions pt-3">
    <%= form.submit :class => "btn btn-primary mr-1" %>
    <%= link_to :back, :class => "btn btn-outline-secondary" do %>Cancel<% end %>
  </div>
<% end %>

  <script>
  
    function toggleEnclosures() {
      if ($("#outcome").val() === "Active") {
        $("#enclosures").show();
        $("#outcome_date").hide();
      } else {
        $("#enclosuresField").val("")
        $("#enclosures").hide();
        $("#outcome_date").show();
      }
    }
    
    $(document).ready(function() {
      toggleEnclosures();
      
      //Initialize date pickers
      $('.datepicker').each(function() {
        $( this ).pickadate({
          format: 'mmmm d, yyyy'
        });
      });
    });
  </script>

app/views/animals/_outcomes.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>

<script>
    var data_raw = '<%= @adoptions %>'
    var data = jQuery.parseJSON(data_raw.replace(/&quot;/g,'"'));


    //set up svg using margin conventions - we'll need plenty of room on the left for labels
    var margin = {
        top: 30,
        right: 40,
        bottom: 0,
        left: 140
    };
    
    var custom_mt = 50
    
    var calc_height = parseInt(data.length, 10) * 50;

    var width = 960 - margin.left - margin.right,
        height = calc_height - margin.top - margin.bottom;
        
    var svg = d3.select(".container:nth-child(2)").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + custom_mt + margin.bottom )
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + custom_mt + ")");

    var x = d3.scale.linear()
        .range([0, width])
        .domain([0, d3.max(data, function (d) {
            return d.totals;
        })]);
    
    var y = d3.scale.ordinal()
        .rangeRoundBands([height, 0], .1)
        .domain(data.map(function (d) {
            return d.outcometype;
        }));

    //make y axis to show bar names
    var yAxis = d3.svg.axis()
        .scale(y)
        //no tick marks
        .tickSize(0)
        .orient("left");

    var gy = svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)

    var bars = svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("g")

    //append rects
    bars.append("rect")
        .attr("class", "bar")
        .attr("y", function (d) {
            return y(d.outcometype);
        })
        .attr("height", y.rangeBand())
        .attr("x", 0)
        .attr("width", function (d) {
            return x(d.totals);
        });

    //add a value label to the right of each bar
    bars.append("text")
        .attr("class", "label")
        //y position of the label is halfway down the bar
        .attr("y", function (d) {
            return y(d.outcometype) + y.rangeBand() / 2 + 4;
        })
        //x position is 3 pixels to the right of the bar
        .attr("x", function (d) {
            return x(d.totals) + 3;
        })
        .text(function (d) {
            return d.totals;
        });
        
</script>
    

app/views/animals/edit.html.erb
<h1 class="my-4">Editing Animal</h1>

<%= render 'form', animal: @animal %>

app/views/animals/index.html.erb
<div class="d-flex my-4 p-0 align-items-baseline">
  <div class="h1 mr-3">Past Animals</div>
  <div class="text-secondary"><%= number_with_delimiter(@results_count, :delimiter => ',') %> results</div>
</div>

<div class="d-flex justify-content-between flex-wrap">
  <div>
  <%= form_tag(animals_path, method: :get) do %>
    <div class="form-row align-items-left">
      <div class="col">
        <%= text_field_tag :name, params[:name], class: "form-control ml-0 mr-2", placeholder: "Name", autocomplete: 'off' %>
      </div>
      <div class="col">
        <%= select_tag :type, options_for_select([ "Bird", "Cat", "Dog", "Livestock", "Other" ], 
            params[:type]), include_blank: "Any Type", class: "form-control ml-0 mr-2", 
            onchange: 'this.form.submit()' %>
      </div>
      <div class="col">
        <%= select_tag :outcometype, options_for_select(["Adoption", "Died", "Euthanasia", "Missing", "Return to Owner", "Transfer"], 
            params[:outcometype]), include_blank: "Any Outcome", class: "form-control ml-0 mr-2",
            onchange: 'this.form.submit()' %>
      </div>
      <div class="col-auto">
        <%= submit_tag 'Search', class: "btn btn-primary" %>
      </div>
      <div class="col-auto">
        <%= link_to 'Clear', animals_path, :class => "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
  </div>
  
  <div>
    <%= will_paginate @animals, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, inner_window: 1  %>
  </div>
</div>

<br>

<table class="table table-light table-hover">
  <thead>
    <tr>
      <th>Outcome Date</th>
      <th>Intake Date</th>
      <th>Name</th>
      <th>Type</th>
      <th>Birthday</th>
      <th>Sex</th>
      <th>Breed</th>
      <th>Outcome</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><% if animal.outcome_date.present? %><%= animal.outcome_date.strftime('%-m/%-d/%Y') %><% end %></td>
        <td><% if animal.intake_date.present? %><%= animal.intake_date.strftime('%-m/%-d/%Y') %><% end %></td>
        <td><%= animal.name %></td>
        <td><%= animal.animaltype %></td>
        <td><% if animal.birthday.present? %><%= animal.birthday.strftime('%-m/%-d/%Y') %><% end %></td>
        <td><%= animal.sex %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.outcometype %></td>
        <td>
          <span class="text-nowrap">
          <%= link_to animal, :class => "hidden mr-1" do %>
            <i class="material-icons">description</i>
          <% end %>

          <%= link_to edit_animal_path(animal), :class => "hidden mr-1" do %>
            <i class="material-icons text-success">edit</i>
          <% end %>

          <%= link_to animal, method: :delete, data: { confirm: 'Are you sure?' }, :class => "hidden" do %>
            <i class="material-icons text-danger">remove_circle</i>
          <% end %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/animals/intakes.html.erb
<div class="d-flex my-4 p-0 align-items-baseline">
  <div class="h1 mr-3">Adoptable Animals</div>
  <div class="text-secondary"><%= "#{pluralize(number_with_delimiter(@animals.count, :delimiter => ','), 'animal')}" %></div>
</div>

<table class="table table-light table-hover">
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Location</th>
      <th>Intake Date</th>
      <th>Sex</th>
      <th>Breed</th>
      <th>Remarks</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.animaltype %></td>
        <td><%= animal.name %></td>
        <td><%= Enclosure.find_by_id(animal.enclosure_id).name %></td>
        <td><% if animal.intake_date.present? %><%= animal.intake_date.strftime('%-m/%-d/%Y') %><% end %></td>
        <td><%= animal.sex %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.outcomesubtype %></td>
        <td>
          <span class="text-nowrap">
          <%= link_to animal, :class => "hidden mr-1" do %>
            <i class="material-icons">description</i>
          <% end %>

          <%= link_to edit_animal_path(animal), :class => "hidden mr-1" do %>
            <i class="material-icons text-success">edit</i>
          <% end %>

          <%= link_to animal, method: :delete, data: { confirm: 'Are you sure?' }, :class => "hidden" do %>
            <i class="material-icons text-danger">remove_circle</i>
          <% end %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/animals/new.html.erb
<h1 class="my-4">New Animal</h1>

<%= render 'form', animal: @animal %>

app/views/animals/show.html.erb
<div class="row">
  <div class="col-3 mt-4 mr-1 ml-auto">
    
    <% if @animal.avatar_file_name.nil? %>
      <%= image_tag "/assets/default_animal_image.png", :class => "img-thumbnail mb-3" %>
    <% else %>
      <%= image_tag @animal.avatar.url, :class => "img-thumbnail mb-3" %>
    <% end %>
        
    <%= link_to 'Edit Details', edit_animal_path(@animal), :class => "btn btn-primary" %>
    <%= link_to 'Back to Animals', :back, :class => "btn btn-outline-primary" %>
  </div>
  <div class="col-5 mr-auto">

    <ul class="list-group py-4">
      <li class="list-group-item active" style="background-color: #ee2740; border-color: #ee2740;">
        <h1 class="ml-3"><%= @animal.name %></h1>
      </li>
      <li class="list-group-item">
          <h6 class="d-inline col-2">Type:</h6><%= @animal.animaltype %>
      </li>
      <li class="list-group-item">
          <h6 class="d-inline col-2">Sex:</h6><%= @animal.sex %>
      </li>
      <li class="list-group-item">
          <h6 class="d-inline col-2">Breed:</h6><%= @animal.breed %>
      </li>
      <li class="list-group-item">
          <h6 class="d-inline col-2">Color:</h6><%= @animal.color %>
      </li>
      <li class="list-group-item">
        <h6 class="d-inline col-2">Birthday:</h6> <% if @animal.birthday.present? %><%= @animal.birthday.strftime('%-m/%-d/%Y') %><% end %>
      </li>
      <% if @animal.outcometype == "Active" %>
        <li class="list-group-item">
          <h6 class="d-inline col-2">Location: </h6> <% if @animal.enclosure_id.present? %><%= Enclosure.find_by_id(@animal.enclosure_id).name %><% end %>
        </li>
      <% else %>
        <li class="list-group-item">
          <h6 class="d-inline col-2">Outcome Date: </h6><% if !@animal.outcome_date.nil?%><%= @animal.outcome_date.strftime('%-m/%-d/%Y') %><% end %>
        </li>
      <% end %>
      <li class="list-group-item">
        <h6 class="d-inline col-2">Intake Date:</h6> <%= @animal.intake_date.strftime('%-m/%-d/%Y') %>
      </li>
      <li class="list-group-item">
        <h6 class="d-inline col-2">Days Active:</h6> 
          <% if @animal.outcometype == "Active" %>
            <%= pluralize((Date.today - @animal.intake_date.to_date + 1).to_i, "day") %>
          <% else %>
            <%= pluralize((@animal.outcome_date.to_date - @animal.intake_date.to_date + 1).to_i, "day") %>
          <% end %>
      </li>
      <li class="list-group-item">
        <h6 class="d-inline col-2">Status: </h6> <%= @animal.outcometype %>
      </li>
      <li class="list-group-item">
        <h6 class="d-inline col-2">Remarks: </h6> <%= @animal.outcomesubtype %>
      </li>
    </ul>

    
  </div>
</div>