config/routes.rb
Rails.application.routes.draw do
  get 'animals/adoptions' => 'animals#adoptions'
  get 'animals/intakes' => 'animals#intakes'
  
  resources :enclosures
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'animals#intakes'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iRESC-U</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= favicon_link_tag asset_path('irescu_favicon.png') %>
    
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white">
      <div class="container py-1 pb-0">
        <%= link_to root_path do %>
          <img src="/assets/irescu_logo.svg" width=160 />
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-4 mr-auto">
            <li class="nav-item dropdown <% if controller.controller_name == "animals" && controller.action_name != "adoptions" %>active<%end%>">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                 Animals
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item <% if controller.action_name == "intakes" %>active<%end%>" href="/animals/intakes">Adoptable Animals</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item <% if controller.controller_name == "animals" && controller.action_name == "index" %>active<%end%>" href="<%= animals_path %>">Past Animals</a>
              </div>
            </li>
            <li class="nav-item <% if controller.controller_name == "enclosures" %>active<% end %>">
              <%= link_to enclosures_path, :class => "nav-link" do %>Map View<% end %>
            </li>
            <li class="nav-item <% if controller.action_name == "adoptions" %>active<% end %>">
              <%= link_to "/animals/adoptions", :class => "nav-link" do %>Reports<% end %>
            </li>
          </ul>
                      
          <span>
            <%= link_to new_animal_path, :class => "btn btn-primary" do %>
             <i class="material-icons d-inline mr-1" style="vertical-align: middle; font-size: 18px; line-height: 1.5;">add_circle_outline</i>
              New Intake
            <% end %>
          </span>
        </div>
    </div>
  </nav>

    <% flash.each do |message_type, message| %>
        <div class="my-0 alert alert-<%= message_type %> alert-dismissible fade show">
          <div class="container">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>

    <div class="container">
        
    
      <%= yield %>
    </div>
  </body>
</html>